import { MaterialYouPalette } from './types'

// TODO: Get default colors from Android. Keep in mind supporting lower API level devices.
export const DEFAULT_PALETTE: MaterialYouPalette = Object.freeze({
  // system_accent1:  [PlatformColor("@android:color/system_accent1_0").toString(), PlatformColor("@android:color/system_accent1_10").toString(), PlatformColor("@android:color/system_accent1_50").toString(), PlatformColor("@android:color/system_accent1_100").toString(), PlatformColor("@android:color/system_accent1_200").toString(), PlatformColor("@android:color/system_accent1_300").toString(), PlatformColor("@android:color/system_accent1_400").toString(), PlatformColor("@android:color/system_accent1_500").toString(), PlatformColor("@android:color/system_accent1_600").toString(), PlatformColor("@android:color/system_accent1_700").toString(), PlatformColor("@android:color/system_accent1_800").toString(), PlatformColor("@android:color/system_accent1_900").toString(), PlatformColor("@android:color/system_accent1_1000").toString()],
  // system_accent2:  [PlatformColor("@android:color/system_accent2_0").toString(), PlatformColor("@android:color/system_accent2_10").toString(), PlatformColor("@android:color/system_accent2_50").toString(), PlatformColor("@android:color/system_accent2_100").toString(), PlatformColor("@android:color/system_accent2_200").toString(), PlatformColor("@android:color/system_accent2_300").toString(), PlatformColor("@android:color/system_accent2_400").toString(), PlatformColor("@android:color/system_accent2_500").toString(), PlatformColor("@android:color/system_accent2_600").toString(), PlatformColor("@android:color/system_accent2_700").toString(), PlatformColor("@android:color/system_accent2_800").toString(), PlatformColor("@android:color/system_accent2_900").toString(), PlatformColor("@android:color/system_accent2_1000").toString()],
  // system_accent3:  [PlatformColor("@android:color/system_accent3_0").toString(), PlatformColor("@android:color/system_accent3_10").toString(), PlatformColor("@android:color/system_accent3_50").toString(), PlatformColor("@android:color/system_accent3_100").toString(), PlatformColor("@android:color/system_accent3_200").toString(), PlatformColor("@android:color/system_accent3_300").toString(), PlatformColor("@android:color/system_accent3_400").toString(), PlatformColor("@android:color/system_accent3_500").toString(), PlatformColor("@android:color/system_accent3_600").toString(), PlatformColor("@android:color/system_accent3_700").toString(), PlatformColor("@android:color/system_accent3_800").toString(), PlatformColor("@android:color/system_accent3_900").toString(), PlatformColor("@android:color/system_accent3_1000").toString()],
  // system_neutral1: [PlatformColor("@android:color/system_neutral1_0").toString(), PlatformColor("@android:color/system_neutral1_10").toString(), PlatformColor("@android:color/system_neutral1_50").toString(), PlatformColor("@android:color/system_neutral1_100").toString(), PlatformColor("@android:color/system_neutral1_200").toString(), PlatformColor("@android:color/system_neutral1_300").toString(), PlatformColor("@android:color/system_neutral1_400").toString(), PlatformColor("@android:color/system_neutral1_500").toString(), PlatformColor("@android:color/system_neutral1_600").toString(), PlatformColor("@android:color/system_neutral1_700").toString(), PlatformColor("@android:color/system_neutral1_800").toString(), PlatformColor("@android:color/system_neutral1_900").toString(), PlatformColor("@android:color/system_neutral1_1000").toString()],
  // system_neutral2: [PlatformColor("@android:color/system_neutral2_0").toString(), PlatformColor("@android:color/system_neutral2_10").toString(), PlatformColor("@android:color/system_neutral2_50").toString(), PlatformColor("@android:color/system_neutral2_100").toString(), PlatformColor("@android:color/system_neutral2_200").toString(), PlatformColor("@android:color/system_neutral2_300").toString(), PlatformColor("@android:color/system_neutral2_400").toString(), PlatformColor("@android:color/system_neutral2_500").toString(), PlatformColor("@android:color/system_neutral2_600").toString(), PlatformColor("@android:color/system_neutral2_700").toString(), PlatformColor("@android:color/system_neutral2_800").toString(), PlatformColor("@android:color/system_neutral2_900").toString(), PlatformColor("@android:color/system_neutral2_1000").toString()],
  system_accent1: [
    '#FFFFFF',
    '#FAFAFA',
    '#F9F9F9',
    '#F8F8F8',
    '#F7F7F7',
    '#F6F6F6',
    '#F5F5F5',
    '#F4F4F4',
    '#F3F3F3',
    '#F2F2F2',
    '#F1F1F1',
    '#EFEFEF',
    '#EEEEEE',
  ],
  system_accent2: [
    '#FFFFFF',
    '#FAFAFA',
    '#F9F9F9',
    '#F8F8F8',
    '#F7F7F7',
    '#F6F6F6',
    '#F5F5F5',
    '#F4F4F4',
    '#F3F3F3',
    '#F2F2F2',
    '#F1F1F1',
    '#EFEFEF',
    '#EEEEEE',
  ],
  system_accent3: [
    '#FFFFFF',
    '#FAFAFA',
    '#F9F9F9',
    '#F8F8F8',
    '#F7F7F7',
    '#F6F6F6',
    '#F5F5F5',
    '#F4F4F4',
    '#F3F3F3',
    '#F2F2F2',
    '#F1F1F1',
    '#EFEFEF',
    '#EEEEEE',
  ],
  system_neutral1: [
    '#FFFFFF',
    '#FAFAFA',
    '#F9F9F9',
    '#F8F8F8',
    '#F7F7F7',
    '#F6F6F6',
    '#F5F5F5',
    '#F4F4F4',
    '#F3F3F3',
    '#F2F2F2',
    '#F1F1F1',
    '#EFEFEF',
    '#EEEEEE',
  ],
  system_neutral2: [
    '#FFFFFF',
    '#FAFAFA',
    '#F9F9F9',
    '#F8F8F8',
    '#F7F7F7',
    '#F6F6F6',
    '#F5F5F5',
    '#F4F4F4',
    '#F3F3F3',
    '#F2F2F2',
    '#F1F1F1',
    '#EFEFEF',
    '#EEEEEE',
  ],
})
